# Generated by Django 3.0.4 on 2022-02-09 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.BooleanField(default=True, verbose_name='trainer')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('training_style', models.CharField(choices=[('powerlifting', 'Powerlifting'), ('bodybuilding', 'Bodybuilding'), ('olympiclifting', 'Olympiclifting'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('bodyweight', 'Bodyweight')], default='powerlifting', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainer',
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee', models.BooleanField(default=True, verbose_name='trainee')),
                ('training_style', models.CharField(choices=[('powerlifting', 'Powerlifting'), ('bodybuilding', 'Bodybuilding'), ('olympiclifting', 'Olympiclifting'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('bodyweight', 'Bodyweight')], default='powerlifting', max_length=25)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Trainer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainee',
            },
        ),
    ]
