# Generated by Django 3.2.5 on 2022-02-22 18:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=100, null=True)),
                ('goal_setting', models.CharField(default='PowerLifting', max_length=50)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(default='Male', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
